<?php
/**
 * WebhookLibraryDocumentEventsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Adobe\ESign\Webhooks
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Adobe\ESign\Webhooks;

/**
 * WebhookLibraryDocumentEventsTest Class Doc Comment
 *
 * @category    Class
 * @description WebhookLibraryDocumentEvents
 * @package     Adobe\ESign\Webhooks
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class WebhookLibraryDocumentEventsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "WebhookLibraryDocumentEvents"
     */
    public function testWebhookLibraryDocumentEvents()
    {
    }

    /**
     * Test attribute "include_detailed_info"
     */
    public function testPropertyIncludeDetailedInfo()
    {
    }

    /**
     * Test attribute "include_documents_info"
     */
    public function testPropertyIncludeDocumentsInfo()
    {
    }
}
