<?php
/**
 * WebhookConditionalParamsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Adobe\ESign\Webhooks
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Adobe\ESign\Webhooks;

/**
 * WebhookConditionalParamsTest Class Doc Comment
 *
 * @category    Class
 * @description WebhookConditionalParams
 * @package     Adobe\ESign\Webhooks
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class WebhookConditionalParamsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "WebhookConditionalParams"
     */
    public function testWebhookConditionalParams()
    {
    }

    /**
     * Test attribute "webhook_widget_events"
     */
    public function testPropertyWebhookWidgetEvents()
    {
    }

    /**
     * Test attribute "webhook_mega_sign_events"
     */
    public function testPropertyWebhookMegaSignEvents()
    {
    }

    /**
     * Test attribute "webhook_library_document_events"
     */
    public function testPropertyWebhookLibraryDocumentEvents()
    {
    }

    /**
     * Test attribute "webhook_agreement_events"
     */
    public function testPropertyWebhookAgreementEvents()
    {
    }
}
