<?php
/**
 * AgreementViewInfo
 *
 * PHP version 5
 *
 * @category Class
 * @package  Adobe\ESign\Agreements
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Adobe\ESign\Agreements\Model;

use \ArrayAccess;
use \Adobe\ESign\Agreements\ObjectSerializer;

/**
 * AgreementViewInfo Class Doc Comment
 *
 * @category Class
 * @package  Adobe\ESign\Agreements
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AgreementViewInfo implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'AgreementViewInfo';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'compose_view_configuration' => '\Adobe\ESign\Agreements\Model\ComposeViewConfiguration',
        'common_view_configuration' => '\Adobe\ESign\Agreements\Model\CommonViewConfiguration',
        'name' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'compose_view_configuration' => null,
        'common_view_configuration' => null,
        'name' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'compose_view_configuration' => 'composeViewConfiguration',
        'common_view_configuration' => 'commonViewConfiguration',
        'name' => 'name'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'compose_view_configuration' => 'setComposeViewConfiguration',
        'common_view_configuration' => 'setCommonViewConfiguration',
        'name' => 'setName'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'compose_view_configuration' => 'getComposeViewConfiguration',
        'common_view_configuration' => 'getCommonViewConfiguration',
        'name' => 'getName'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const NAME_COMPOSE = 'COMPOSE';
    const NAME_MODIFY = 'MODIFY';
    const NAME_PREFILL = 'PREFILL';
    const NAME_AUTHORING = 'AUTHORING';
    const NAME_SEND_PROGRESS = 'SEND_PROGRESS';
    const NAME_POST_CREATE = 'POST_CREATE';
    const NAME_DOCUMENT = 'DOCUMENT';
    const NAME_MANAGE = 'MANAGE';
    const NAME_SIGNING = 'SIGNING';
    const NAME_ALL = 'ALL';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getNameAllowableValues()
    {
        return [
            self::NAME_COMPOSE,
            self::NAME_MODIFY,
            self::NAME_PREFILL,
            self::NAME_AUTHORING,
            self::NAME_SEND_PROGRESS,
            self::NAME_POST_CREATE,
            self::NAME_DOCUMENT,
            self::NAME_MANAGE,
            self::NAME_SIGNING,
            self::NAME_ALL,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['compose_view_configuration'] = isset($data['compose_view_configuration']) ? $data['compose_view_configuration'] : null;
        $this->container['common_view_configuration'] = isset($data['common_view_configuration']) ? $data['common_view_configuration'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getNameAllowableValues();
        if (!is_null($this->container['name']) && !in_array($this->container['name'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'name', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets compose_view_configuration
     *
     * @return \Adobe\ESign\Agreements\Model\ComposeViewConfiguration
     */
    public function getComposeViewConfiguration()
    {
        return $this->container['compose_view_configuration'];
    }

    /**
     * Sets compose_view_configuration
     *
     * @param \Adobe\ESign\Agreements\Model\ComposeViewConfiguration $compose_view_configuration Compose page view configuration
     *
     * @return $this
     */
    public function setComposeViewConfiguration($compose_view_configuration)
    {
        $this->container['compose_view_configuration'] = $compose_view_configuration;

        return $this;
    }

    /**
     * Gets common_view_configuration
     *
     * @return \Adobe\ESign\Agreements\Model\CommonViewConfiguration
     */
    public function getCommonViewConfiguration()
    {
        return $this->container['common_view_configuration'];
    }

    /**
     * Sets common_view_configuration
     *
     * @param \Adobe\ESign\Agreements\Model\CommonViewConfiguration $common_view_configuration Common view configuration for all the available views
     *
     * @return $this
     */
    public function setCommonViewConfiguration($common_view_configuration)
    {
        $this->container['common_view_configuration'] = $common_view_configuration;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name Name of the requested agreement view
     *
     * @return $this
     */
    public function setName($name)
    {
        $allowedValues = $this->getNameAllowableValues();
        if (!is_null($name) && !in_array($name, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'name', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['name'] = $name;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


