<?php
/**
 * WidgetCreationInfoV6Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Adobe\ESign\Widgets
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Adobe\ESign\Widgets;

/**
 * WidgetCreationInfoV6Test Class Doc Comment
 *
 * @category    Class
 * @description WidgetCreationInfoV6
 * @package     Adobe\ESign\Widgets
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class WidgetCreationInfoV6Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "WidgetCreationInfoV6"
     */
    public function testWidgetCreationInfoV6()
    {
    }

    /**
     * Test attribute "additional_participant_sets_info"
     */
    public function testPropertyAdditionalParticipantSetsInfo()
    {
    }

    /**
     * Test attribute "creator_email"
     */
    public function testPropertyCreatorEmail()
    {
    }

    /**
     * Test attribute "locale"
     */
    public function testPropertyLocale()
    {
    }

    /**
     * Test attribute "vaulting_info"
     */
    public function testPropertyVaultingInfo()
    {
    }

    /**
     * Test attribute "security_option"
     */
    public function testPropertySecurityOption()
    {
    }

    /**
     * Test attribute "widget_participant_set_info"
     */
    public function testPropertyWidgetParticipantSetInfo()
    {
    }

    /**
     * Test attribute "ccs"
     */
    public function testPropertyCcs()
    {
    }

    /**
     * Test attribute "created_date"
     */
    public function testPropertyCreatedDate()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "completion_info"
     */
    public function testPropertyCompletionInfo()
    {
    }

    /**
     * Test attribute "auth_failure_info"
     */
    public function testPropertyAuthFailureInfo()
    {
    }

    /**
     * Test attribute "file_infos"
     */
    public function testPropertyFileInfos()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }
}
