<?php
/**
 * WebhookConditionalParams
 *
 * PHP version 5
 *
 * @category Class
 * @package  Adobe\ESign\Webhooks
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Adobe\ESign\Webhooks\Model;

use \ArrayAccess;
use \Adobe\ESign\Webhooks\ObjectSerializer;

/**
 * WebhookConditionalParams Class Doc Comment
 *
 * @category Class
 * @package  Adobe\ESign\Webhooks
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class WebhookConditionalParams implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'WebhookConditionalParams';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'webhook_widget_events' => '\Adobe\ESign\Webhooks\Model\WebhookWidgetEvents',
        'webhook_mega_sign_events' => '\Adobe\ESign\Webhooks\Model\WebhookMegaSignEvents',
        'webhook_library_document_events' => '\Adobe\ESign\Webhooks\Model\WebhookLibraryDocumentEvents',
        'webhook_agreement_events' => '\Adobe\ESign\Webhooks\Model\WebhookAgreementEvents'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'webhook_widget_events' => null,
        'webhook_mega_sign_events' => null,
        'webhook_library_document_events' => null,
        'webhook_agreement_events' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'webhook_widget_events' => 'webhookWidgetEvents',
        'webhook_mega_sign_events' => 'webhookMegaSignEvents',
        'webhook_library_document_events' => 'webhookLibraryDocumentEvents',
        'webhook_agreement_events' => 'webhookAgreementEvents'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'webhook_widget_events' => 'setWebhookWidgetEvents',
        'webhook_mega_sign_events' => 'setWebhookMegaSignEvents',
        'webhook_library_document_events' => 'setWebhookLibraryDocumentEvents',
        'webhook_agreement_events' => 'setWebhookAgreementEvents'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'webhook_widget_events' => 'getWebhookWidgetEvents',
        'webhook_mega_sign_events' => 'getWebhookMegaSignEvents',
        'webhook_library_document_events' => 'getWebhookLibraryDocumentEvents',
        'webhook_agreement_events' => 'getWebhookAgreementEvents'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['webhook_widget_events'] = isset($data['webhook_widget_events']) ? $data['webhook_widget_events'] : null;
        $this->container['webhook_mega_sign_events'] = isset($data['webhook_mega_sign_events']) ? $data['webhook_mega_sign_events'] : null;
        $this->container['webhook_library_document_events'] = isset($data['webhook_library_document_events']) ? $data['webhook_library_document_events'] : null;
        $this->container['webhook_agreement_events'] = isset($data['webhook_agreement_events']) ? $data['webhook_agreement_events'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets webhook_widget_events
     *
     * @return \Adobe\ESign\Webhooks\Model\WebhookWidgetEvents
     */
    public function getWebhookWidgetEvents()
    {
        return $this->container['webhook_widget_events'];
    }

    /**
     * Sets webhook_widget_events
     *
     * @param \Adobe\ESign\Webhooks\Model\WebhookWidgetEvents $webhook_widget_events Conditional parameters for webhook widget events
     *
     * @return $this
     */
    public function setWebhookWidgetEvents($webhook_widget_events)
    {
        $this->container['webhook_widget_events'] = $webhook_widget_events;

        return $this;
    }

    /**
     * Gets webhook_mega_sign_events
     *
     * @return \Adobe\ESign\Webhooks\Model\WebhookMegaSignEvents
     */
    public function getWebhookMegaSignEvents()
    {
        return $this->container['webhook_mega_sign_events'];
    }

    /**
     * Sets webhook_mega_sign_events
     *
     * @param \Adobe\ESign\Webhooks\Model\WebhookMegaSignEvents $webhook_mega_sign_events Conditional parameters for webhook megasign events
     *
     * @return $this
     */
    public function setWebhookMegaSignEvents($webhook_mega_sign_events)
    {
        $this->container['webhook_mega_sign_events'] = $webhook_mega_sign_events;

        return $this;
    }

    /**
     * Gets webhook_library_document_events
     *
     * @return \Adobe\ESign\Webhooks\Model\WebhookLibraryDocumentEvents
     */
    public function getWebhookLibraryDocumentEvents()
    {
        return $this->container['webhook_library_document_events'];
    }

    /**
     * Sets webhook_library_document_events
     *
     * @param \Adobe\ESign\Webhooks\Model\WebhookLibraryDocumentEvents $webhook_library_document_events Conditional parameters for webhook library document events
     *
     * @return $this
     */
    public function setWebhookLibraryDocumentEvents($webhook_library_document_events)
    {
        $this->container['webhook_library_document_events'] = $webhook_library_document_events;

        return $this;
    }

    /**
     * Gets webhook_agreement_events
     *
     * @return \Adobe\ESign\Webhooks\Model\WebhookAgreementEvents
     */
    public function getWebhookAgreementEvents()
    {
        return $this->container['webhook_agreement_events'];
    }

    /**
     * Sets webhook_agreement_events
     *
     * @param \Adobe\ESign\Webhooks\Model\WebhookAgreementEvents $webhook_agreement_events Conditional parameters for webhook agreement events
     *
     * @return $this
     */
    public function setWebhookAgreementEvents($webhook_agreement_events)
    {
        $this->container['webhook_agreement_events'] = $webhook_agreement_events;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


