<?php
/**
 * LibraryViewTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Adobe\ESign\LibraryDocuments
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Adobe\ESign\LibraryDocuments;

/**
 * LibraryViewTest Class Doc Comment
 *
 * @category    Class
 * @description LibraryView
 * @package     Adobe\ESign\LibraryDocuments
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LibraryViewTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "LibraryView"
     */
    public function testLibraryView()
    {
    }

    /**
     * Test attribute "is_current"
     */
    public function testPropertyIsCurrent()
    {
    }

    /**
     * Test attribute "embedded_code"
     */
    public function testPropertyEmbeddedCode()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "expiration"
     */
    public function testPropertyExpiration()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }
}
