<?php
/**
 * ComposeViewConfigurationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Adobe\ESign\Agreements
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Adobe\ESign\Agreements;

/**
 * ComposeViewConfigurationTest Class Doc Comment
 *
 * @category    Class
 * @description ComposeViewConfiguration
 * @package     Adobe\ESign\Agreements
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ComposeViewConfigurationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ComposeViewConfiguration"
     */
    public function testComposeViewConfiguration()
    {
    }

    /**
     * Test attribute "file_upload_options"
     */
    public function testPropertyFileUploadOptions()
    {
    }

    /**
     * Test attribute "is_preview_selected"
     */
    public function testPropertyIsPreviewSelected()
    {
    }
}
