<?php
/**
 * OfflineDeviceInfoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Adobe\ESign\Agreements
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Adobe\ESign\Agreements;

/**
 * OfflineDeviceInfoTest Class Doc Comment
 *
 * @category    Class
 * @description OfflineDeviceInfo
 * @package     Adobe\ESign\Agreements
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OfflineDeviceInfoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "OfflineDeviceInfo"
     */
    public function testOfflineDeviceInfo()
    {
    }

    /**
     * Test attribute "device_description"
     */
    public function testPropertyDeviceDescription()
    {
    }

    /**
     * Test attribute "application_description"
     */
    public function testPropertyApplicationDescription()
    {
    }

    /**
     * Test attribute "device_time"
     */
    public function testPropertyDeviceTime()
    {
    }
}
