<?php
/**
 * LibraryDocumentsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Adobe\ESign\LibraryDocuments
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Adobe\ESign\LibraryDocuments;

use \Adobe\ESign\LibraryDocuments\Configuration;
use \Adobe\ESign\LibraryDocuments\ApiException;
use \Adobe\ESign\LibraryDocuments\ObjectSerializer;

/**
 * LibraryDocumentsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Adobe\ESign\LibraryDocuments
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class LibraryDocumentsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createLibraryDocument
     *
     * Creates a template that is placed in the library of the user for reuse..
     *
     */
    public function testCreateLibraryDocument()
    {
    }

    /**
     * Test case for createLibraryDocumentView
     *
     * Retrieves the latest state view url of a library document..
     *
     */
    public function testCreateLibraryDocumentView()
    {
    }

    /**
     * Test case for getAllDocumentsOfLibraryDocument
     *
     * Retrieves the IDs of the documents associated with library document..
     *
     */
    public function testGetAllDocumentsOfLibraryDocument()
    {
    }

    /**
     * Test case for getAllLibraryDocuments
     *
     * Retrieves library documents for a user..
     *
     */
    public function testGetAllLibraryDocuments()
    {
    }

    /**
     * Test case for getDocumentImageUrlsOfLibraryDocument
     *
     * Retrieves image urls of all visible pages of a document associated with a library document..
     *
     */
    public function testGetDocumentImageUrlsOfLibraryDocument()
    {
    }

    /**
     * Test case for getDocumentOfLibraryDocument
     *
     * Retrieves the file stream of a document of library document..
     *
     */
    public function testGetDocumentOfLibraryDocument()
    {
    }

    /**
     * Test case for getLibraryDocumentAuditTrail
     *
     * Retrieves the audit trail associated with a library document..
     *
     */
    public function testGetLibraryDocumentAuditTrail()
    {
    }

    /**
     * Test case for getLibraryDocumentCombinedDocument
     *
     * Retrieves the combined document associated with a library document..
     *
     */
    public function testGetLibraryDocumentCombinedDocument()
    {
    }

    /**
     * Test case for getLibraryDocumentEvents
     *
     * Retrieves the events information for a library document..
     *
     */
    public function testGetLibraryDocumentEvents()
    {
    }

    /**
     * Test case for getLibraryDocumentFormData
     *
     * Retrieves data entered into the interactive form fields of the library document..
     *
     */
    public function testGetLibraryDocumentFormData()
    {
    }

    /**
     * Test case for getLibraryDocumentInfo
     *
     * Retrieves the details of a library document..
     *
     */
    public function testGetLibraryDocumentInfo()
    {
    }

    /**
     * Test case for getLibraryDocumentNoteForApiUser
     *
     * Retrieves the latest note of a library document for the API user..
     *
     */
    public function testGetLibraryDocumentNoteForApiUser()
    {
    }

    /**
     * Test case for updateLibraryDocument
     *
     * Updates the library document..
     *
     */
    public function testUpdateLibraryDocument()
    {
    }

    /**
     * Test case for updateLibraryDocumentNoteForApiUser
     *
     * Updates the latest note of a library document for the API user..
     *
     */
    public function testUpdateLibraryDocumentNoteForApiUser()
    {
    }

    /**
     * Test case for updateLibraryDocumentState
     *
     * Updates the library document's state..
     *
     */
    public function testUpdateLibraryDocumentState()
    {
    }

    /**
     * Test case for updateLibraryDocumentVisibility
     *
     * Updates the visibility of library document..
     *
     */
    public function testUpdateLibraryDocumentVisibility()
    {
    }
}
