<?php
/**
 * GroupUsersInfoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Adobe\ESign\Groups
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Adobe\ESign\Groups;

/**
 * GroupUsersInfoTest Class Doc Comment
 *
 * @category    Class
 * @description GroupUsersInfo
 * @package     Adobe\ESign\Groups
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GroupUsersInfoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GroupUsersInfo"
     */
    public function testGroupUsersInfo()
    {
    }

    /**
     * Test attribute "user_info_list"
     */
    public function testPropertyUserInfoList()
    {
    }

    /**
     * Test attribute "page"
     */
    public function testPropertyPage()
    {
    }
}
