<?php
/**
 * FormFieldConditionalActionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * FormFieldConditionalActionTest Class Doc Comment
 *
 * @category    Class
 * @description Conditional actions to perfom on this form field.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FormFieldConditionalActionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FormFieldConditionalAction"
     */
    public function testFormFieldConditionalAction()
    {
    }

    /**
     * Test attribute "predicates"
     */
    public function testPropertyPredicates()
    {
    }

    /**
     * Test attribute "any_or_all"
     */
    public function testPropertyAnyOrAll()
    {
    }

    /**
     * Test attribute "action"
     */
    public function testPropertyAction()
    {
    }
}
