<?php
/**
 * MegaSignCreationInfoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * MegaSignCreationInfoTest Class Doc Comment
 *
 * @category    Class
 * @description MegaSignCreationInfo
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MegaSignCreationInfoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MegaSignCreationInfo"
     */
    public function testMegaSignCreationInfo()
    {
    }

    /**
     * Test attribute "ccs"
     */
    public function testPropertyCcs()
    {
    }

    /**
     * Test attribute "child_agreements_info"
     */
    public function testPropertyChildAgreementsInfo()
    {
    }

    /**
     * Test attribute "created_date"
     */
    public function testPropertyCreatedDate()
    {
    }

    /**
     * Test attribute "expiration_time"
     */
    public function testPropertyExpirationTime()
    {
    }

    /**
     * Test attribute "external_id"
     */
    public function testPropertyExternalId()
    {
    }

    /**
     * Test attribute "file_infos"
     */
    public function testPropertyFileInfos()
    {
    }

    /**
     * Test attribute "first_reminder_delay"
     */
    public function testPropertyFirstReminderDelay()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "locale"
     */
    public function testPropertyLocale()
    {
    }

    /**
     * Test attribute "message"
     */
    public function testPropertyMessage()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "post_sign_option"
     */
    public function testPropertyPostSignOption()
    {
    }

    /**
     * Test attribute "reminder_frequency"
     */
    public function testPropertyReminderFrequency()
    {
    }

    /**
     * Test attribute "security_option"
     */
    public function testPropertySecurityOption()
    {
    }

    /**
     * Test attribute "sender_email"
     */
    public function testPropertySenderEmail()
    {
    }

    /**
     * Test attribute "signature_type"
     */
    public function testPropertySignatureType()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "vaulting_info"
     */
    public function testPropertyVaultingInfo()
    {
    }
}
