<?php
/**
 * SendViewConfiguration
 *
 * PHP version 5
 *
 * @category Class
 * @package  Adobe\ESign\LibraryDocuments
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Adobe\ESign\LibraryDocuments\Model;

use \ArrayAccess;
use \Adobe\ESign\LibraryDocuments\ObjectSerializer;

/**
 * SendViewConfiguration Class Doc Comment
 *
 * @category Class
 * @package  Adobe\ESign\LibraryDocuments
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SendViewConfiguration implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'SendViewConfiguration';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'file_upload_options' => '\Adobe\ESign\LibraryDocuments\Model\FileUploadOptions',
        'is_preview_selected' => 'bool',
        'agr_name' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'file_upload_options' => null,
        'is_preview_selected' => null,
        'agr_name' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'file_upload_options' => 'fileUploadOptions',
        'is_preview_selected' => 'isPreviewSelected',
        'agr_name' => 'agrName'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'file_upload_options' => 'setFileUploadOptions',
        'is_preview_selected' => 'setIsPreviewSelected',
        'agr_name' => 'setAgrName'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'file_upload_options' => 'getFileUploadOptions',
        'is_preview_selected' => 'getIsPreviewSelected',
        'agr_name' => 'getAgrName'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['file_upload_options'] = isset($data['file_upload_options']) ? $data['file_upload_options'] : null;
        $this->container['is_preview_selected'] = isset($data['is_preview_selected']) ? $data['is_preview_selected'] : null;
        $this->container['agr_name'] = isset($data['agr_name']) ? $data['agr_name'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets file_upload_options
     *
     * @return \Adobe\ESign\LibraryDocuments\Model\FileUploadOptions
     */
    public function getFileUploadOptions()
    {
        return $this->container['file_upload_options'];
    }

    /**
     * Sets file_upload_options
     *
     * @param \Adobe\ESign\LibraryDocuments\Model\FileUploadOptions $file_upload_options Controls various file upload options available on the compose page
     *
     * @return $this
     */
    public function setFileUploadOptions($file_upload_options)
    {
        $this->container['file_upload_options'] = $file_upload_options;

        return $this;
    }

    /**
     * Gets is_preview_selected
     *
     * @return bool
     */
    public function getIsPreviewSelected()
    {
        return $this->container['is_preview_selected'];
    }

    /**
     * Sets is_preview_selected
     *
     * @param bool $is_preview_selected Should the compose page be provided with authoring mode selected?
     *
     * @return $this
     */
    public function setIsPreviewSelected($is_preview_selected)
    {
        $this->container['is_preview_selected'] = $is_preview_selected;

        return $this;
    }

    /**
     * Gets agr_name
     *
     * @return string
     */
    public function getAgrName()
    {
        return $this->container['agr_name'];
    }

    /**
     * Sets agr_name
     *
     * @param string $agr_name The agreement name for the library document on the compose page
     *
     * @return $this
     */
    public function setAgrName($agr_name)
    {
        $this->container['agr_name'] = $agr_name;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


